import { MigrationInterface, QueryRunner } from "typeorm";

export class FakeShows1612628746499 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        insert into show (title, year) values ('Get Low', 1993);
insert into show (title, year) values ('Lady Death', 2008);
insert into show (title, year) values ('One Shot', 2010);
insert into show (title, year) values ('Gentlemen Prefer Blondes', 1990);
insert into show (title, year) values ('Lord Love a Duck', 2010);
insert into show (title, year) values ('Santa''s Pocket Watch', 1990);
insert into show (title, year) values ('Air Up There, The', 2009);
insert into show (title, year) values ('Sport, Sport, Sport', 1991);
insert into show (title, year) values ('Slumdog Millionaire', 2011);
insert into show (title, year) values ('Proof of Life', 2010);
insert into show (title, year) values ('Cet amour-là', 1996);
insert into show (title, year) values ('Look Both Ways', 1995);
insert into show (title, year) values ('Wild Things', 1993);
insert into show (title, year) values ('Man Is Not a Bird (Covek nije tica)', 2010);
insert into show (title, year) values ('Teacher, A', 1985);
insert into show (title, year) values ('Ransom', 2001);
insert into show (title, year) values ('We Feed the World', 2008);
insert into show (title, year) values ('Budd Boetticher: An American Original ', 1997);
insert into show (title, year) values ('Broadway Damage', 1997);
insert into show (title, year) values ('Taming of the Shrew, The', 1985);
insert into show (title, year) values ('Rare Exports: A Christmas Tale (Rare Exports)', 1991);
insert into show (title, year) values ('Wild One, The', 2005);
insert into show (title, year) values ('Koumiko Mystery, The (Mystère Koumiko, Le)', 2007);
insert into show (title, year) values ('Faith School Menace?', 2009);
insert into show (title, year) values ('Gas, Food, Lodging', 2012);
insert into show (title, year) values ('Romance on the High Seas', 2000);
insert into show (title, year) values ('Batman: The Dark Knight Returns, Part 2', 2007);
insert into show (title, year) values ('Music for One Apartment and Six Drummers', 2010);
insert into show (title, year) values ('Quiet, The', 2006);
insert into show (title, year) values ('Red Elvis, The (Der rote Elvis)', 2000);
insert into show (title, year) values ('Nobody Knows (Dare mo shiranai)', 1995);
insert into show (title, year) values ('Ultramarines: A Warhammer 40,000 Movie', 1992);
insert into show (title, year) values ('It Boy (20 ans d''écart)', 1992);
insert into show (title, year) values ('Last Run, The', 2010);
insert into show (title, year) values ('Skin I Live In, The (La piel que habito)', 2002);
insert into show (title, year) values ('Scanners', 1993);
insert into show (title, year) values ('Era of Vampires, The', 2012);
insert into show (title, year) values ('Dr. Jekyll and Mr. Hyde', 1965);
insert into show (title, year) values ('En rachâchant', 1998);
insert into show (title, year) values ('Go', 2005);
insert into show (title, year) values ('Law, The (a.k.a. Where the Hot Wind Blows!) (Legge, La)', 1999);
insert into show (title, year) values ('101 Dalmatians II: Patch''s London Adventure', 1993);
insert into show (title, year) values ('Cincinnati Kid, The', 2008);
insert into show (title, year) values ('Super Troopers', 2012);
insert into show (title, year) values ('Mister Magoo''s Christmas Carol', 2010);
insert into show (title, year) values ('Examined Life', 1998);
insert into show (title, year) values ('I Hate But Love (Nikui an-chikushô)', 2003);
insert into show (title, year) values ('Def-Con 4', 2012);
insert into show (title, year) values ('Raincoat', 1999);
insert into show (title, year) values ('Star of Midnight', 2002);
insert into show (title, year) values ('Cargo 200 (Gruz 200)', 1988);
insert into show (title, year) values ('Wrestling for Jesus: The Tale of T-Money', 1997);
insert into show (title, year) values ('Even the Rain (También la lluvia)', 2002);
insert into show (title, year) values ('Christmas Vacation (National Lampoon''s Christmas Vacation)', 2004);
insert into show (title, year) values ('Dead Man and Being Happy, The (El muerto y ser feliz)', 1993);
insert into show (title, year) values ('Logan''s War: Bound by Honor', 2006);
insert into show (title, year) values ('One and Only, The', 1998);
insert into show (title, year) values ('Little Murders', 1992);
insert into show (title, year) values ('Rain', 2002);
insert into show (title, year) values ('Merry-Go-Round', 2004);
insert into show (title, year) values ('Take This Job and Shove It', 2000);
insert into show (title, year) values ('Trash Humpers', 1999);
insert into show (title, year) values ('Gamera vs. Viras ', 1990);
insert into show (title, year) values ('Mrs. Henderson Presents', 2005);
insert into show (title, year) values ('Carabineers, The (Carabiniers, Les)', 2004);
insert into show (title, year) values ('Producers, The', 2009);
insert into show (title, year) values ('Battle for the Planet of the Apes', 2003);
insert into show (title, year) values ('Atlas Shrugged: Part II', 1998);
insert into show (title, year) values ('Homer & Eddie', 2013);
insert into show (title, year) values ('Crystal Ball, The', 1991);
insert into show (title, year) values ('Bounty, The', 1995);
insert into show (title, year) values ('Hour of the Furnaces, The (Hora de los hornos, La)', 2006);
insert into show (title, year) values ('Under the Age', 2004);
insert into show (title, year) values ('Hello Herman', 2012);
insert into show (title, year) values ('Without Bias (a.k.a. Len Bias)', 2002);
insert into show (title, year) values ('Marat/Sade', 2009);
insert into show (title, year) values ('Cabin in the Sky', 2005);
insert into show (title, year) values ('Little Nicky', 1986);
insert into show (title, year) values ('In the Park', 1968);
insert into show (title, year) values ('A Good Marriage', 2000);
insert into show (title, year) values ('Cocoanuts, The', 1997);
insert into show (title, year) values ('Naked Souls', 1986);
insert into show (title, year) values ('Stagecoach', 1996);
insert into show (title, year) values ('Orderers (Les ordres)', 2006);
insert into show (title, year) values ('My Favorite Martian', 1997);
insert into show (title, year) values ('Shed No Tears (Känn ingen sorg)', 1992);
insert into show (title, year) values ('Cruising', 2006);
insert into show (title, year) values ('Chain Letter', 2002);
insert into show (title, year) values ('P.S. Your Cat is Dead', 2011);
insert into show (title, year) values ('Halo Legends', 1991);
insert into show (title, year) values ('Once', 1989);
insert into show (title, year) values ('Amen', 2002);
insert into show (title, year) values ('New Best Friend', 2004);
insert into show (title, year) values ('Then She Found Me', 1988);
insert into show (title, year) values ('Enron: The Smartest Guys in the Room', 2011);
insert into show (title, year) values ('Melinda and Melinda', 2003);
insert into show (title, year) values ('Locusts, The', 2013);
insert into show (title, year) values ('Watership Down', 1996);
insert into show (title, year) values ('Brass Monkey', 2006);
insert into show (title, year) values ('Deal, The', 1994); `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
